In [1]:
import pandas as pd
df = pd.read_csv('iris_dataset.csv')
print(df.head())

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa


In [14]:
import matplotlib.pyplot as plt
import pandas as pd
from numpy import genfromtxt
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, confusion_matrix, f1_score,
                             precision_score, recall_score)
#algo
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler

#--------read data--------#

#X components
features = genfromtxt('iris_dataset.csv', delimiter=',',
                      usecols=tuple(range(0, 4)), dtype=float, skip_header=1)

#Y components
class_value = genfromtxt('iris_dataset.csv', delimiter=',',
                         usecols=(-1), dtype=str, skip_header=1)

#labels
labels = LabelEncoder().fit_transform(class_value)

#scale the data
features_normalized = StandardScaler().fit_transform(features)

#training and testing sets (preprocessing)
x_train, x_test, y_train, y_test = train_test_split(features_normalized, labels, test_size=0.30, random_state=0)
#-------------------#


#--function to print stats--#
def print_stats_metrics(y_test, y_pred):
  print('Accuracy is: %.2f' % accuracy_score(y_test,y_pred))
  print('F1 measure is: %.3f' % f1_score(y_test, y_pred, average='weighted'))
  print('Recall is: %.3f' % recall_score(y_test,y_pred, average='weighted'))
  print('Precision is: %.3f' % precision_score(y_test, y_pred, average='weighted'))
  #method 1
  conf_mat = confusion_matrix(y_test, y_pred)
  print(conf_mat)

  #method 2
  print(pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'],
                    margins=True))
#-------------------#


#Implementing SVMs - support vector machine
svm1 = svm.SVC() #version of svm
svm1.fit(x_train, y_train)
y_pred = svm1.predict(x_test)
print_stats_metrics(y_test, y_pred)

print("-Done-")

Accuracy is: 0.93
F1 measure is: 0.932
Recall is: 0.933
Precision is: 0.944
[[16  0  0]
 [ 0 16  0]
 [ 0  3 10]]
Predicted   0   1   2  All
True                      
0          16   0   0   16
1           0  16   0   16
2           0   3  10   13
All        16  19  10   45
-Done-
